# Generated by Django 4.1.7 on 2023-09-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='found_year',
            field=models.CharField(help_text='masalan 2019 va 2023 yani found date', max_length=255),
        ),
    ]
