# Generated by Django 4.1.7 on 2023-09-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tariflar',
            field=models.CharField(blank=True, choices=[(1, 'Международный рынок'), (2, 'Европейский рынок'), (3, 'Азиатский рынок'), (4, 'Рынок Узбекистана')], max_length=100, null=True),
        ),
    ]
