# Generated by Django 4.1.7 on 2023-09-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_mode_in_alter_application_tariflar'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
