# Generated by Django 4.1.7 on 2023-08-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_subcategory_subcategorytranslation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='typeproducttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='typeproducttranslation',
            name='master',
        ),
        migrations.AlterField(
            model_name='company',
            name='type_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Maxsulot turi'),
        ),
        migrations.DeleteModel(
            name='TypeProduct',
        ),
        migrations.DeleteModel(
            name='TypeProductTranslation',
        ),
    ]
