# Generated by Django 4.1.7 on 2023-09-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_question_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytranslation',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='short_description'),
        ),
    ]
