# Generated by Django 4.1.7 on 2023-09-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_companytranslation_short_description'),
    ]

    operations = [
    ]
