# Generated by Django 4.1.7 on 2023-08-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_typeproducttranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='campany',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.company'),
            preserve_default=False,
        ),
    ]
