# Generated by Django 4.1.7 on 2023-08-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_campany'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='post_images', verbose_name='Rasm'),
            preserve_default=False,
        ),
    ]
