# Generated by Django 4.1.7 on 2023-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20230920_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='short_description',
            field=models.TextField(blank=True, default='NEW', null=True, verbose_name='short_description'),
        ),
    ]
