# Generated by Django 4.1.7 on 2023-09-09 10:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_company_country_alter_company_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytranslation',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='compound',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
